language: node_js
node_js:
  - "lts/*"
before_install:
  - npm i -g npm
script:
  - npm run lint
  - npm run test:coverage
  - npm run build
after_script: 
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
    - master
